setwd("~/mindset/formdisc")
library(DBI)
dbt=dbConnect(RSQLite::SQLite(), dbname='transactions.db')
tabtrans = dbGetQuery( dbt,'select * from payments' )
View(tabtrans)
dbDisconnect(dbt)
dbu=dbConnect(RSQLite::SQLite(), dbname='profiles.sqlite')
tabtrand = dbGetQuery( dbu,'select * from disc' )
View(tabtrand)
dbDisconnect(dbu)
